# Generated by Django 5.2.8 on 2026-07-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_helpcategory_helparticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='promotions/')),
                ('button_text', models.CharField(default='Shop Now', max_length=30)),
                ('link', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
