# Generated by Django 5.2.7 on 2025-11-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='review_avatars/'),
        ),
    ]
