# Generated by Django 5.2.8 on 2026-08-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_supportticket_attachment_ticketreply_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticketmessage',
            name='voice_message',
            field=models.FileField(blank=True, null=True, upload_to='support/customer/voice/'),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='voice_message',
            field=models.FileField(blank=True, null=True, upload_to='support/agent/voice/'),
        ),
    ]
