# Generated by Django 5.2.8 on 2026-08-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customerticketmessage_voice_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='voice_message',
            field=models.FileField(blank=True, null=True, upload_to='support/customer/voice/'),
        ),
    ]
