# Generated by Django 5.2.8 on 2025-11-25

from django.db import migrations, models
from django.utils.text import slugify


def populate_unique_subcategory_slugs(apps, schema_editor):
    SubCategory = apps.get_model('core', 'SubCategory')

    for sub in SubCategory.objects.all():
        # Generate initial slug
        base_slug = slugify(sub.name) or "subcategory"
        slug = base_slug
        counter = 1

        # Ensure uniqueness
        while SubCategory.objects.filter(slug=slug).exclude(id=sub.id).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        sub.slug = slug
        sub.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True, null=True),
        ),

        # Populate slugs before enforcing NOT NULL
        migrations.RunPython(populate_unique_subcategory_slugs, migrations.RunPython.noop),

        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),

        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
