# Generated by Django 5.2.8 on 2026-09-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='row2_image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/row2/'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='row2_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
