# Generated by Django 5.2.7 on 2025-11-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The original price before discount', max_digits=10, null=True),
        ),
    ]
