# Generated by Django 5.2.8 on 2025-11-25

from django.db import migrations, models
from django.utils.text import slugify

def generate_unique_slugs(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    existing_slugs = set()

    for category in Category.objects.all():
        # Start slug from name
        base_slug = slugify(category.name) or "category"

        slug = base_slug
        counter = 1

        # Ensure uniqueness
        while slug in existing_slugs:
            slug = f"{base_slug}-{counter}"
            counter += 1

        existing_slugs.add(slug)

        # Save slug
        category.slug = slug
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_initial_price'),
    ]

    operations = [
        # 1️⃣ Add slug WITHOUT unique=True
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),

        # 2️⃣ Populate unique slugs
        migrations.RunPython(generate_unique_slugs, migrations.RunPython.noop),

        # 3️⃣ Make slug unique
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
