# Generated by Django 5.2.8 on 2025-11-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_supportticket_ticketreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_clearance',
            field=models.BooleanField(default=False),
        ),
    ]
